"""empty message

Revision ID: 074281625e1e
Revises: 40e194db2d1b
Create Date: 2020-06-01 07:34:57.847542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074281625e1e'
down_revision = '40e194db2d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.VARCHAR(length=5), nullable=True))
    # ### end Alembic commands ###
